### ISSUE TITLE
How can I turn off popup showing answer? It's annoying

### ISSUE THREAD

**Issue by huduvn** [noobj2/Anki-Review-PopUp#10]
Thanks for updating this addon but this version have a funtion is showing popup when press answer. It's very annoying. How can I turn it off?

**Comment by noobj2** [comment]
You should've been able to disable it by setting show answer pop-up chance on 0. But i forgot to set the minimum for that on 0, so in this version it's not possible to disable it. Gonna push an update in a couple of hours to fix that.

**Comment by noobj2** [comment]
It's been fixed for a while, had forgotten to close the issue -_-
