### ISSUE TITLE
Remove popup button & frame

### ISSUE THREAD

**Issue by Jfaler** [noobj2/Anki-Review-PopUp#11]
Hello, thank you so much for creating this addon :)! I'm trying to remove the frame & button for the popup. So far I got it to work without the button & frame but now I can't click out of the qDialog. How do I set it where I can click anywhere or use a short timer to hide the qDialog before the next card? Thanks again.

I added these lines.
```
  window.setWindowFlag(Qt.FramelessWindowHint)
  window.setAttribute(Qt.WA_TranslucentBackground, True)
```
<img width="692" alt="error" src="https://user-images.githubusercontent.com/8336385/103164401-ad7e6700-47bf-11eb-9745-7a4f9dc7b7df.PNG">

**Comment by noobj2** [comment]
modified it pretty nice :D well done
I think I'll do the same and update the add-on when I have some free time.

anyways, to make the window close when you click anywhere you should use this:
`window.setWindowFlags(Qt.FramelessWindowHint | Qt.Popup)`

**Comment by Jfaler** [comment]
Yay It works now but how do I make it instead of clicking anywhere to any key that is pressed? This is what I have so far.
```
window.setWindowFlags(Qt.FramelessWindowHint | Qt.Popup | Qt.NoDropShadowWindowHint)
```

**Comment by noobj2** [comment]
hey, sorry for the late reply -_- been really busy with life lately
I don't know how to implement that atm -_-
I'll try to help you with that in a couple of months

**Comment by noobj2** [comment]
Frameless window with the ability to close the pop-up upon clicking outside the pop-up and by pressing any key on the keyboard added in the latest version [2.0.0](https://github.com/noobj2/Anki-Review-PopUp/releases/tag/v2.0.0)
