### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dobibo** [noobj2/Anki-Review-PopUp#12]
Been getting this error too much, can't use the addon anymore, please help me :( 

Note: I use audio for button clicks, and disabled photo popup 

Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-04-10 06:54:04

Caught exception:
Traceback (most recent call last):
  File "aqt\reviewer.py", line 298, in <lambda>
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-56>", line 2, in _answerCard
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 632, in repl
  File "C:\Users\Carnage\AppData\Roaming\Anki2\addons21\976516370\Review_PopUp.py", line 56, in myPopUp
    show_popUp(cnt, ease)
  File "C:\Users\Carnage\AppData\Roaming\Anki2\addons21\976516370\Review_PopUp.py", line 124, in show_popUp
    image_name = '/{}'.format(random.choice(imageName_list))
  File "random.py", line 290, in choice
IndexError: Cannot choose from an empty sequence

**Comment by noobj2** [comment]
I think I fixed that in the last update -_-
anyways, until I get some time to work on the add-ons again (in about 2-3 months, hopefully) I suggest not emptying the image/audio/video folders.

now to solve your problem: go to `Tools -> add-ons` and select `Answer visual auditory custom text reinforcement` (a mouthful, I know lol) and then press `View files`. Then go to `user_files` and make sure all the `again/hard/good/easy` folders contain at least one file (image file for images folder and audio file for audio folder)
this should solve your problem

**Comment by dobibo** [comment]
> I think I fixed that in the last update -_-
> anyways, until I get some time to work on the add-ons again (in about 2-3 months, hopefully) I suggest not emptying the image/audio/video folders.
> 
> now to solve your problem: go to `Tools -> add-ons` and select `Answer visual auditory custom text reinforcement` (a mouthful, I know lol) and then press `View files`. Then go to `user_files` and make sure all the `again/hard/good/easy` folders contain at least one file (image file for images folder and audio file for audio folder)
> this should solve your problem

Thanks for the quick reply .  
Now I just need to find a the right image to pop everytime.

**Comment by noobj2** [comment]
nope actually, if you don't want any image to pop, you can just disable the option in add-on settings.
the thing is, the image folder should not be empty

**Comment by dobibo** [comment]
Oh , Awesome.
Just so you know the popup made me actually utilize anki, Really
appreciate it.

‫בתאריך יום ב׳, 12 באפר׳ 2021 ב-14:13 מאת ‪noobj2‬‏ <‪
***@***.***‬‏>:‬

**Comment by noobj2** [comment]
glad to hear that <3
