### ISSUE TITLE
Image Reinforcement Not Working In Other Decks

### ISSUE THREAD

**Issue by CcHhDdOo** [noobj2/Anki-Review-PopUp#13]
When I switch the deck I only get the audio reinforcement, but not the visual pop up. The deck where I used it the first time is working without any problems. (v 2.1.40)

**Comment by noobj2** [comment]
I'll look into it when I get some free time -_-
I'll do my best to free up some time to fix the bugs of this add-on within a week (2 weeks maybe) -_-
been really busy irl lately

**Comment by noobj2** [comment]
Fixed all the issues for the latest version of Anki. Everything should be working fine now.
Also, sorry for the late reply -_- I'd totally forgotten about this.
