### ISSUE TITLE
Images with big resolutions cover leave out of the screen and the bottom to close the pop up is hidden.

### ISSUE THREAD

**Issue by CaptainDead** [noobj2/Anki-Review-PopUp#16]
If some of my images are big then it takes over most of the screen and the button to close the pop up is also hidden. 
For example: look at the images in the bottom.

![Screenshot 2024-02-07 015955](https://github.com/noobj2/Anki-Review-PopUp/assets/139457914/e839d5fe-0056-4e64-950a-041ad8b87762)
![Screenshot 2024-02-07 015934](https://github.com/noobj2/Anki-Review-PopUp/assets/139457914/84aa3946-30ef-4459-8cdb-e3828020423a)

In the above images, the popup leaves the screen and we can't see the close bottom in the bottom, and we cant resize the pop up either. for now, I use esc. button on the keyboard to close such images and next thing I will take a screenshot in such a way so that the whole image can fit in the image and the button is not hidden.

Please make some sort of change by which the image automatically gets shrinked w/o changing the resolution/shape and can be seen in the middle like the normal small images.
Example: ![image](https://github.com/noobj2/Anki-Review-PopUp/assets/139457914/fe209a24-7223-4d4b-a1d4-47e3d701c893)

The button is visible, the whole image is visible, so add some changes by which the images automatically gets resized or something.
I hope the problem was clear and was not confusing, thanks for this amazing addon.

**Comment by noobj2** [comment]
Hey
Thanks for the report
I'll try to fix it in a few days

**Comment by CaptainDead** [comment]
> Hey Thanks for the report I'll try to fix it in a few days

Sure thanks, take your time... For now I am just using this site to resize my images so that they can fit in the screen, its easy so its not a big problem for me as I can manage.

Will leave this link here if someone else might need it - https://imageresizer.com/bulk-resize
we can resize all the images at once here

**Comment by noobj2** [comment]
Added in the latest version [2.0.0](https://github.com/noobj2/Anki-Review-PopUp/releases/tag/v2.0.0)

**Comment by CaptainDead** [comment]
umm I reinstalled the addon but now everytime I start Anki I get this error - 
![image](https://github.com/noobj2/Anki-Review-PopUp/assets/139457914/7332a842-e63b-4574-8bb7-0fe1b568aea9)

The addon is working but I get this error and I also can't find the settings under tools, are they located somewhere else now?

**Comment by noobj2** [comment]
Can you copy the debug info and send it here?

**Comment by CaptainDead** [comment]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22621

When loading Answer visual  auditory  custom text reinforcement:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\capta\AppData\Roaming\Anki2\addons21\976516370\__init__.py", line 8, in <module>
    from . import Settings2
  File "C:\Users\capta\AppData\Roaming\Anki2\addons21\976516370\Settings2.py", line 36, in <module>
    class Settings(QDialog):
  File "C:\Users\capta\AppData\Roaming\Anki2\addons21\976516370\Settings2.py", line 37, in Settings
    refreshConfig()
  File "C:\Users\capta\AppData\Roaming\Anki2\addons21\976516370\Settings2.py", line 20, in refreshConfig
    C_play_videoGif = config["Play Video/Gif"]
KeyError: 'Play Video/Gif'

**Comment by noobj2** [comment]
it should be fixed now

**Comment by CaptainDead** [comment]
Thanks its working now🙏
But I am really curious as to why you removed the option to be able to use both video and image/text together, I really liked it, so like if possible woudn't it be better to have both? like if someone doesn't want the video with images/text they can just not select it.
Thanks for the addon

**Comment by noobj2** [comment]
This is what happens when both of them are enabled at the same time in the new version.
honestly, it doesn't make sense as the video immediately closes the image and header and removes them.
Looks like a bug and it's also distracting.

https://github.com/noobj2/Anki-Review-PopUp/assets/63994740/7161b622-77f6-4b9d-aabd-51edd99c80c2

**Comment by CaptainDead** [comment]
So you are saying that the image/text pop up is closed once the video ends or when it starts, right? if that's the case then it can't be helped so its alright.

But if the problem is that its distracting as video pops up with the image/text popup, then that is not a problem at all, I really like that, I have videos only for when I click on 'hard' and 'again', so its fun when I get to see a video once in a while
Here see this lol (turn on sound):

https://github.com/noobj2/Anki-Review-PopUp/assets/139457914/743623b5-9122-4d8e-a5ca-c3a649eada16

well if the problem is the first one (which it probably is) and it can't be fixed then its okay, thanks for the add on, I love it a lot... I wish there was Pomodoro app like this that shows pops up like that after custom intervals
Thanks for the addon🙏

**Comment by noobj2** [comment]
IMO the frameless window looks a lot better. But with the way you use the framed window, I probably will add it again later and let the users choose between the two.
