### ISSUE TITLE
BUG: The add-on crashes after trying to open the images or audio folder 

### ISSUE THREAD

**Issue by sevazre** [noobj2/Anki-Review-PopUp#5]
The add-on crashes after trying to open the images or audio folder by pressing these bottoms in the add-on's menu window.
This is the roport I got from Anki:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-12 08:38:59
Add-ons possibly involved: ⁨Answer visual  auditory  custom text reinforcement⁩

Caught exception:
Traceback (most recent call last):
  File "/home/*****/.local/share/Anki2/addons21/976516370/Settings2.py", line 113, in <lambda>
    imagesFolder_button.clicked.connect(lambda: os.startfile(images))
AttributeError: module 'os' has no attribute 'startfile'

**Comment by noobj2** [comment]
Thanks for the report.
changed how it handles opening folders. can you test it again? can't test it myself, don't have linux!

**Comment by sevazre** [comment]
It works fine now, thanks!!

**Comment by noobj2** [comment]
happy to hear that!
and thanks again for the reposrt
