### ISSUE TITLE
Thanks again and small request

### ISSUE THREAD

**Issue by ParadoxicalEmboli** [noobj2/Anki-Review-PopUp#7]
Hello! Thank you again and just wanted to put this request here as well: is it possible to have the "show answer" button also have a sound, and possibly the "suspend" button as well? 

this is fantastic Addon, I really hope you keep updating it!

**Comment by noobj2** [comment]
I'll try to add that as soon as I get some free time to work on the add-ons again -_-
no promise to add those soon tho, but I'll do my best to add the as soon as I possibly can

**Comment by noobj2** [comment]
done
