### ISSUE TITLE
sounds not consistently playing

### ISSUE THREAD

**Issue by 75462565374252** [noobj2/Anki-Review-PopUp#9]
First of all thanks for making this add-on, it's great in principle.

However, it has never consistently worked for me. It will play the sounds only about half the time. It's even more apparent now that it's possible to have a sound for showing the answer too.

Anything I can do? Newest Anki version on newest MacOS Catalina.

**Comment by noobj2** [comment]
can you check if Pop-Up Chance (Tools -> Review Pop-Up Settings -> Pop-Up Chance) is set on 100%?

**Comment by 75462565374252** [comment]
Yes it is.

**Comment by noobj2** [comment]
I have tested it many times on windows, plays audio every time. As i don't have a mac, can't test add-ons on mac. You can email me at mamad.jj98@gmail.com and test different possible fixes that that i send you and see which one works -_-

**Comment by noobj2** [comment]
I have tested it many times on windows, plays audio every time. As i don't have a mac, can't test add-ons on mac. You can email me at mamad.jj98@gmail.com and test different possible fixes that that i send you and see which one works -_-
